### PR TITLE
updated images and text to match

### PR DESCRIPTION
**Pull request by kerrywatson1**
@electronwill  please see TODO in this image and LMK how to insert the image I already uploaded to both repos per docs readme.

### CODE REVIEW

**Comment by electronwill** [comment]
Sure! I went ahead and merged the new images in https://github.com/ContinuumIO/docs/pull/235 and https://github.com/ContinuumIO/Docs-D7/pull/233 .

I'm not seeing the option to publish it to the Test branch in Drupal at dashboard.pantheon.io. @maxgamurar, do you know why?

**Comment by electronwill** [comment]
For the rst file, I made a new commit to this branch so that now in the text where you want the image to appear there is ``|Anaconda Cloud user toolbar|``, and at the bottom of the page there is:

``.. |Anaconda Cloud user toolbar| image:: /img/managing-toolbar-menu.png``

Once the Drupal merge is done we can merge this PR, build and deploy the docs, and the image will display.

**Comment by maxgamurar** [comment]
@electronwill please check https://github.com/ContinuumIO/Docs-D7/pull/233

**Comment by electronwill** [comment]
@maxgamurar it's working great now. Thank you!

**Comment by electronwill** [comment]
@kerrywatson1 OK, this PR will now replace https://docs.continuum.io/_images/cloud-home.jpg with https://docs.continuum.io/_images/cloud-home.png and replace https://docs.continuum.io/_images/cloud-user-toolbar.jpg with https://docs.continuum.io/_images/managing-toolbar-bar.png on the page https://docs.continuum.io/anaconda-cloud/managing-account . Where should https://docs.continuum.io/_images/managing-toolbar-menu.png go?

**Comment by electronwill** [comment]
@kerrywatson1 never mind-- I see now that it's clear from the text where that image should go, so I added it.

**Pull request merged**
